name: deploy

on:
  push:
    branches:
      - master

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build Site
        uses: josefadamcik/actions/publisher@master
        with:
          entrypoint: /build.sh

      - name: Publish Site
        uses: josefadamcik/actions/publisher@master
        env:
          JEKYLL_DEPLOY_KEY: ${{ secrets.JEKYLL_DEPLOY_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        with:
          entrypoint: /publish.sh

      - name: Send Notification
        uses: Clivern/pushover-actions@0.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}