name: deploy

on:
  push:
    branches:
      - master
    

jobs:
  run-deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
#      FIXME: if I endup using this again, I shoulld delete that after building (now it's getting uploaded to the deployment)
#       - name: Checkout markdown resume
#         uses: actions/checkout@master
#         with: 
#           repository: josefadamcik/markdown-resume
#           path: markdown-resume
#           ref: mytemplate-rebased

#       - name: Install wkhtmltopdf
#         run: |
#           sudo apt update
#           sudo apt install wkhtmltopdf

#       - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: '7.4'

#       - name: Install markdown-resume dependencies
#         working-directory: markdown-resume
#         run: |
#           php --version
#           composer install --no-interaction

#       - name: Build resume
#         run:  ./build_resume.sh

      - name: Build Site
        uses: josefadamcik/actions/publisher@master
        with:
          entrypoint: /build.sh

#       - uses: actions/upload-artifact@v2
#         with:
#           name: resume.pdf
#           path: resume.pdf

#       - uses: actions/upload-artifact@v2
#         with:
#           name: resume.html
#           path: resume.html
          
      - name: Publish Site
        uses: josefadamcik/actions/publisher@master
        env:
          JEKYLL_DEPLOY_KEY: ${{ secrets.JEKYLL_DEPLOY_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        with:
          entrypoint: /publish.sh

      - name: Push Build Status Notifications
        if: ${{ always() }}
        uses: desiderati/github-action-pushover@v1
        with:
          job-status: ${{ job.status }}
          pushover-api-token: ${{ secrets.PUSHOVER_TOKEN }}
          pushover-user-key: ${{ secrets.PUSHOVER_USER }}
