name: deploy

on:
  push:
    # branches:
      # - master
    

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Checkout markdown resume
        uses: actions/checkout@master
        repository: josefadamcik/markdown-resume
        path: markdown-resume

      - name: Install wkhtmltopdf
        run: sudo apt install wkhtmltopdf

      - name: Build resume
        run:  ./build_resume.sh

      - name: Build Site
        uses: josefadamcik/actions/publisher@master
        with:
          entrypoint: /build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: resume.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: resume.html
          path: resume.html
          
      # - name: Publish Site
      #   uses: josefadamcik/actions/publisher@master
      #   env:
      #     JEKYLL_DEPLOY_KEY: ${{ secrets.JEKYLL_DEPLOY_KEY }}
      #     DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      #     DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      #     DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
      #     DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      #   with:
      #     entrypoint: /publish.sh

      # - name: Push Build Status Notifications
      #   if: ${{ always() }}
      #   uses: desiderati/github-action-pushover@v1
      #   with:
      #     job-status: ${{ job.status }}
      #     pushover-api-token: ${{ secrets.PUSHOVER_TOKEN }}
      #     pushover-user-key: ${{ secrets.PUSHOVER_USER }}
